### ISSUE TITLE
Algoritmos y estructuras de datos

### ISSUE THREAD

**Issue by luisparracamara** [joseluistello/Helena#1]
Yo recomiendo este libro en español, a mi me ayudó bastante: Estructura de datos en java de Luis Joyanes

link: https://lc.fie.umich.mx/~a1039048f/nts/Documents/Estructura%20de%20datos%20en%20java%20Joyanes%201ed.pdf

**Comment by joseluistello** [comment]
Listo! lo agregue a la categoria de Software Engineering y a la [Subcategoria de Java](https://drive.google.com/drive/u/2/folders/1mCIKRLAs2uOl5KwbDfVFVPRLNcfV-pmf)
